services:
  web:
    image: nginx:latest
    environment:
      # https://stackoverflow.com/questions/56649582/substitute-environment-variables-in-nginx-config-from-docker-compose
      PHP_HOST: php
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".conf"
    ports:
      - '5001:80'
    volumes:
      - ./src/static:/var/www/html
      - ./conf/nginx:/etc/nginx/templates
    depends_on:
      - php
      - db
  php:
    # Includes mysqli, which the built-in php:8-fpm does not have
    image: nanoninja/php-fpm:latest
    environment:
      MARIADB_HOST: db
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./src/php:/var/www/html
  db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - "./src/db/schema.sql:/docker-entrypoint-initdb.d/0.sql"
      - "./src/db/seed.sql:/docker-entrypoint-initdb.d/1.sql"
  admin:
    image: phpmyadmin:latest
    ports:
      - '5002:80'
    environment:
      PMA_HOST: db
      PMA_USER: ${MARIADB_USER}
      PMA_PASSWORD: ${MARIADB_PASSWORD}
    depends_on:
      - db
