services:
  web:
    image: ${DOCKER_LIBRARY}/${DOCKER_APPNAME}-web
    build:
      dockerfile: ./docker/web/Dockerfile
    environment:
      PHP_HOST: php
    ports:
      - '5001:80'
    depends_on:
      - php
      - db
  php:
    image: ${DOCKER_LIBRARY}/${DOCKER_APPNAME}-php
    build:
      dockerfile: ./docker/php/Dockerfile
    environment:
      MARIADB_HOST: db
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
  db:
    image: ${DOCKER_LIBRARY}/${DOCKER_APPNAME}-db
    build:
      dockerfile: ./docker/db/Dockerfile
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - '3306:3306'
  admin:
    image: phpmyadmin:latest
    ports:
      - '5002:80'
    environment:
      PMA_HOST: db
      PMA_USER: ${MARIADB_USER}
      PMA_PASSWORD: ${MARIADB_PASSWORD}
    depends_on:
      - db
