services:
  web:
    image: nginx:latest
    ports:
      - '5001:80'
    volumes:
      - ./src/static:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    image: php:8-fpm
    volumes:
      - ./src/php:/var/www/html
