services:
  web:
    build:
      dockerfile: ./docker/web/Dockerfile
    environment:
      PHP_HOST: php
    ports:
      - '5001:80'
    depends_on:
      - php
      - db
  php:
    build:
      dockerfile: ./docker/php/Dockerfile
    environment:
      MARIADB_HOST: db
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
  db:
    image: mariadb:10.6
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - "./src/db/schema.sql:/docker-entrypoint-initdb.d/0.sql"
      - "./src/db/seed.sql:/docker-entrypoint-initdb.d/1.sql"
  admin:
    image: phpmyadmin:latest
    ports:
      - '5002:80'
    environment:
      PMA_HOST: db
      PMA_USER: ${MARIADB_USER}
      PMA_PASSWORD: ${MARIADB_PASSWORD}
    depends_on:
      - db
