services:
  web:
    image: nginx:latest
    ports:
      - '5001:80'
    volumes:
      - ./src/static:/var/www/html
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
  php:
    image: php:8-fpm
    volumes:
      - ./src/php:/var/www/html
  db:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=development
      - MARIADB_DATABASE=hello
      - MARIADB_USER=dev
      - MARIADB_PASSWORD=internal
